### ISSUE TITLE
missing pagelabels/README.md in the pypi archive

### ISSUE THREAD

**Issue by teto** [lovasoa/pagelabels-py#5]
When trying to install 1.0.1 from pip (would be nice to tag the repo as well), I get:
 ```
Executing setuptoolsBuildPhase
Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 21, in <module>
    long_description=open("pagelabels/README.md", "r").read(),
FileNotFoundError: [Errno 2] No such file or directory: 'pagelabels/README.md'
note: keeping build directory '/tmp/nix-build-python3.7-pagelabels-1.0.1.drv-0'
```

and indeed it seems the archive lacks the README.md
```
tmp/nix-build-python3.7-pagelabels-1.0.1.drv-0/pagelabels-1.0.1 
❯ ls pagelabels
__init__.py  pagelabelscheme.py  pagelabels.py
```

**Comment by lovasoa** [comment]
Hello !
  What exactly are you trying to do ?
  The README is included in the source release, but not in the wheel : https://pypi.org/project/pagelabels/#files
  I am no expert in this field, but it seems to be the way other libraries are packaged.

**Comment by teto** [comment]
I am no python expert either but according to https://pythonwheels.com/ : 
`Wheels are the new standard of Python distribution and are intended to replace eggs. Support is offered in pip >= 1.4 and setuptools >= 0.8`
So I should be able to install from the wheel as well. This is the default way of installing packages on my distrib (www.nixos.org), admittedly because it's faster or the last standard. Would you mind adding the readme to the wheel too please ?

**Comment by lovasoa** [comment]
How does your distribution handle other python packages, such as pip or requests ? All the other packages I've looked at do not include a README in their wheel archive. I packaged pagelabels using [the official guide on python.org](https://packaging.python.org/tutorials/packaging-projects/), I doubt that these instructions lead to incorrect packages...

**Comment by teto** [comment]
so the distrib tries to create a wheel from the source package with pip bdist_wheel but that fails because README.md is not in the source distrib https://files.pythonhosted.org/packages/4b/79/fba3745c79b7327af5ee64bb2382a86a85ff5529dd8515f2ad783fdbc102/pagelabels-1.0.1.tar.gz

**Comment by lovasoa** [comment]
I think it is: https://pypi.org/project/pagelabels/#files
`README.md` is at the root of the tar.gz file your link points to.

**Comment by lovasoa** [comment]
```
$ curl -s 'https://files.pythonhosted.org/packages/4b/79/fba3745c79b7327af5ee64bb2382a86a85ff5529dd8515f2ad783fdbc102/pagelabels-1.0.1.tar.gz' | tar -ztvf -
drwxr-xr-x  0 o      users       0 Nov 15  2018 pagelabels-1.0.1/
-rw-r--r--  0 o      users    2793 Nov 15  2018 pagelabels-1.0.1/PKG-INFO
-rw-r--r--  0 o      users    2478 Nov 15  2018 pagelabels-1.0.1/README.md
drwxr-xr-x  0 o      users       0 Nov 15  2018 pagelabels-1.0.1/pagelabels/
-rwxr-xr-x  0 o      users     148 Nov 15  2018 pagelabels-1.0.1/pagelabels/__init__.py
-rw-r--r--  0 o      users    1837 Nov 15  2018 pagelabels-1.0.1/pagelabels/pagelabels.py
-rw-r--r--  0 o      users    2320 Nov 15  2018 pagelabels-1.0.1/pagelabels/pagelabelscheme.py
drwxr-xr-x  0 o      users       0 Nov 15  2018 pagelabels-1.0.1/pagelabels.egg-info/
-rw-r--r--  0 o      users    2793 Nov 15  2018 pagelabels-1.0.1/pagelabels.egg-info/PKG-INFO
-rw-r--r--  0 o      users     265 Nov 15  2018 pagelabels-1.0.1/pagelabels.egg-info/SOURCES.txt
-rw-r--r--  0 o      users       1 Nov 15  2018 pagelabels-1.0.1/pagelabels.egg-info/dependency_links.txt
-rw-r--r--  0 o      users       6 Nov 15  2018 pagelabels-1.0.1/pagelabels.egg-info/requires.txt
-rw-r--r--  0 o      users      11 Nov 15  2018 pagelabels-1.0.1/pagelabels.egg-info/top_level.txt
-rw-r--r--  0 o      users      38 Nov 15  2018 pagelabels-1.0.1/setup.cfg
-rw-r--r--  0 o      users     958 Nov 15  2018 pagelabels-1.0.1/setup.py
```

**Comment by teto** [comment]
it lacks pagelabels/README.md that is referenced in setup.py for the long description

**Comment by lovasoa** [comment]
OK, I see what you are talking about, now. I'm going to fix that.

**Comment by lovasoa** [comment]
I added the file to the source distribution.

```
$ curl -s 'https://files.pythonhosted.org/packages/a9/83/fe0c77355688743bd8591bd97809dcbf34d9c1c93e360cb7cfe5e8381a30/pagelabels-1.0.2.tar.gz' | tar -tvf -
drwxr-xr-x  0 olojkine staff       0 Sep 26 14:50 pagelabels-1.0.2/
-rw-r--r--  0 olojkine staff      29 Sep 26 14:50 pagelabels-1.0.2/MANIFEST.in
-rw-r--r--  0 olojkine staff    2793 Sep 26 14:50 pagelabels-1.0.2/PKG-INFO
-rw-r--r--  0 olojkine staff    3720 Sep 26 14:34 pagelabels-1.0.2/README.md
drwxr-xr-x  0 olojkine staff       0 Sep 26 14:50 pagelabels-1.0.2/pagelabels/
-rw-r--r--  0 olojkine staff    1657 Sep 26 14:34 pagelabels-1.0.2/pagelabels/README.md
-rwxr-xr-x  0 olojkine staff     148 Sep 26 14:34 pagelabels-1.0.2/pagelabels/__init__.py
-rw-r--r--  0 olojkine staff    1837 Sep 26 14:34 pagelabels-1.0.2/pagelabels/pagelabels.py
-rw-r--r--  0 olojkine staff    2320 Sep 26 14:34 pagelabels-1.0.2/pagelabels/pagelabelscheme.py
drwxr-xr-x  0 olojkine staff       0 Sep 26 14:50 pagelabels-1.0.2/pagelabels.egg-info/
-rw-r--r--  0 olojkine staff    2793 Sep 26 14:50 pagelabels-1.0.2/pagelabels.egg-info/PKG-INFO
-rw-r--r--  0 olojkine staff     298 Sep 26 14:50 pagelabels-1.0.2/pagelabels.egg-info/SOURCES.txt
-rw-r--r--  0 olojkine staff       1 Sep 26 14:50 pagelabels-1.0.2/pagelabels.egg-info/dependency_links.txt
-rw-r--r--  0 olojkine staff       6 Sep 26 14:50 pagelabels-1.0.2/pagelabels.egg-info/requires.txt
-rw-r--r--  0 olojkine staff      11 Sep 26 14:50 pagelabels-1.0.2/pagelabels.egg-info/top_level.txt
-rw-r--r--  0 olojkine staff      38 Sep 26 14:50 pagelabels-1.0.2/setup.cfg
-rw-r--r--  0 olojkine staff     958 Sep 26 14:44 pagelabels-1.0.2/setup.py
```

I also added tags to this repo.

**Comment by teto** [comment]
thanks for everything, that fixed it hourra \o/
